#!/usr/bin/env python3
"""Build the site from src/site.html.

The main site is one page: the hero and its four sections, reached by the nav
anchors, exactly as before. What changes is the footer. Careers, Privacy,
Terms of Use and Disclaimer were panels that opened over whatever you were
reading; each is now a page with an address of its own, so it can be linked,
bookmarked, cited in correspondence and read on its own terms. LinkedIn is
someone else's site and stays an outbound link.

src/site.html stays the single source of truth. Nothing here rewrites copy --
sections and notices move wholesale, and the build fails loudly if a piece it
expects is missing.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = (ROOT / "src/site.html").read_text(encoding="utf-8")

CSS_OUT = ROOT / "assets/css/site.css"
JS_OUT = ROOT / "assets/js/site.js"


def one(pattern, label, flags=re.S):
    m = re.findall(pattern, SRC, flags)
    if len(m) != 1:
        sys.exit(f"FAIL [{label}]: expected 1 match, found {len(m)}")
    return m[0]


head = one(r"<head>(.*?)</head>", "head")
restoration = one(r'(<script id="pdcm-scroll-restoration">.*?</script>)', "restoration")
fonts = "\n".join(re.findall(r'<link rel="preconnect"[^>]*>|<link href="https://fonts\.googleapis[^>]*>', head))
if not fonts:
    sys.exit("FAIL: font links not found")

styles = re.findall(r"<style[^>]*>(.*?)</style>", head, re.S)
if len(styles) != 5:
    sys.exit(f"FAIL: expected 5 style blocks, found {len(styles)}")

body = one(r"<body[^>]*>(.*?)</body>", "body")
nav = one(r"(<nav id=\"nav\">.*?</nav>)", "nav")
hero = one(r"(<header class=\"hero\" id=\"top\">.*?</header>)", "hero")
footer = one(r"(<footer>.*?</footer>)", "footer")
entry_gate = one(r'(<div class="disclaimer-modal" id="entryDisclaimerModal".*?</div>\s*</div>\s*</div>)', "entry gate")

sections = [one(r'(<section id="%s".*?</section>)' % s, "section " + s)
            for s in ("firm", "approach", "values", "contact")]

# Each former panel keeps its contents exactly; only its container changes.
def panel(modal_id):
    return one(r'<div class="disclaimer-modal" id="%s".*?<div class="disclaimer-content">(.*?)\s*</div>\s*</div>\s*</div>'
               % modal_id, "panel " + modal_id)

PANELS = {"careers": panel("careersModal"), "privacy": panel("privacyModal"),
          "terms": panel("termsModal"), "disclaimer": panel("disclaimerModal")}

scripts = re.findall(r"<script(?![^>]*\bsrc=)(?![^>]*pdcm-scroll-restoration)[^>]*>(.*?)</script>", body, re.S)
if len(scripts) < 7:
    sys.exit(f"FAIL: expected the page's scripts, found {len(scripts)}")


css = "\n".join(styles)

# The nav on a footer page, which has no hero to sit over and so needs the
# treatment it would otherwise only get once you had scrolled. Mirrored from
# the nav.scrolled rules rather than restated, so the two cannot drift.
mirrored = []
for rule in re.findall(r"([^{}]*nav\.scrolled[^{}]*)\{([^{}]*)\}", css):
    sel = ", ".join(s.strip().replace("nav.scrolled", "body.page-light nav")
                    for s in rule[0].split(",") if "nav.scrolled" in s)
    if sel:
        mirrored.append(f"{sel} {{{rule[1]}}}")
if len(mirrored) < 4:
    sys.exit(f"FAIL: expected to mirror the nav.scrolled rules, mirrored {len(mirrored)}")

CLEARANCE = ",\n".join("body.page-inner main > section#" + i for i in ("page", "notfound"))

EXTRA_CSS = """

/* ════════════════════════════════════════════════
   Generated by src/build_pages.py
   ════════════════════════════════════════════════ */

/* ── The hero's lower edge ────────────────────────
   The hero used to stop dead against the section below it -- a hard line
   across the page where a dark field met a pale one. This dissolves it: a
   band of the following section's colour, rising out of the bottom of the
   hero. It is driven by scroll position rather than by a one-way animation,
   so it resolves as you come down and returns as you go back up, and it is
   the same gesture in both directions.

   The band belongs to the hero rather than to the section below so that it
   sits over the moving light field and blends with whatever the field is
   doing at that moment, instead of cutting across it. */

/* The dissolve itself lives in the hero-field stylesheet in src/site.html,
   which owns this layer with !important; a rule here could not beat it. */

/* The section below deliberately adds nothing of its own. An earlier version
   gave #firm a navy head meant to meet the hero halfway, but the hero has
   already resolved to the paper colour by the time it ends -- so tinting the
   top of the section darker than the rest of it did not soften the join, it
   introduced a second edge a few pixels below the first. Measured as a band
   still visible at the seam. The hero's dissolve reaching full paper is the
   whole effect. */

/* Nothing moves under reduced motion, so the join is simply always made. */
/* ── The last row ─────────────────────────────────
   The hero's fade lands on exactly the paper colour through its whole run --
   251,250,246, measured two rows above the edge, matching the section below
   channel for channel. Its FINAL row alone renders 252,251,247: one unit
   brighter in every channel. That is an artifact of how Chromium resolves a
   gradient's last row, not a colour reachable by choosing different stops --
   a flat, fully opaque tail rendered the same way, and made it worse by
   adding a step of 7 where the tail met the ramp.

   One unit is nothing in isolation. As a straight line across 1200px of flat
   field it is the whole complaint. Since the row cannot be corrected it is
   covered: the section below starts two pixels higher and paints its own
   paper over it. It needs a stacking context to do so, because the hero is
   positioned and would otherwise paint above it. */
#firm {
  position: relative;
  z-index: 1;
  margin-top: -2px;
}

/* ── Room for the fade ────────────────────────────
   The hero was exactly one screen tall with its text sitting 100px off the
   bottom, which left the fade nowhere to go: at its previous length it
   already ran 182px up behind the sub-headline, and running it further would
   have washed the text out rather than made the transition smoother.

   The hero is taller than the window now, and its text is held higher within
   it. The extra height is empty ground below the text for the gradient to
   occupy, so the fade can be long without passing behind anything that has
   to stay legible. At rest the window still shows a full screen of hero with
   no fade at all; the fade is what you scroll into.

   It was briefly taller still -- 190vh -- to buy the fade more scroll to run
   across. That is not what a longer fade means: it lengthened the landing
   page rather than the effect, and made you scroll further to reach anything.
   The height is back where it was, and the smoothness comes from the fade's
   own length and from easing the value over time instead. */
.hero {
  height: 130vh;
  min-height: 960px;
  padding-bottom: max(200px, 42vh);
}

@media (max-width: 700px) {
  .hero { height: 124vh; min-height: 700px; padding-bottom: max(150px, 34vh); }
}

/* The final settle onto the page's own colour. Sized from the same scroll
   value that drives the fade, so it grows and unwinds with it. */
.hero-foot {
  position: absolute;
  left: 0; right: 0; bottom: 0;
  height: calc(var(--hero-fade, 0px) * 0.26);
  z-index: 2;
  pointer-events: none;
  background: linear-gradient(180deg,
    rgba(251, 250, 246, 0) 0%,
    rgba(251, 250, 246, 0.18) 34%,
    rgba(251, 250, 246, 0.52) 60%,
    rgba(251, 250, 246, 0.82) 80%,
    rgba(251, 250, 246, 0.96) 92%,
    rgba(251, 250, 246, 1) 100%);
}

/* ── Footer pages ─────────────────────────────────
   Cross-document view transitions. Chrome and Safari animate between the
   main page and a footer page; Firefox ignores the at-rule and navigates
   normally, which is the correct fallback rather than a broken one. Naming
   the nav and footer keeps them still while the content changes. */
@view-transition { navigation: auto; }

nav { view-transition-name: pdcm-nav; }
footer { view-transition-name: pdcm-footer; }

::view-transition-old(root) { animation: pdcmPageOut 0.30s cubic-bezier(.4, 0, 1, 1) both; }
::view-transition-new(root) { animation: pdcmPageIn 0.46s cubic-bezier(.16, 1, .3, 1) both; }
@keyframes pdcmPageOut { to   { opacity: 0; transform: translateY(-10px); } }
@keyframes pdcmPageIn  { from { opacity: 0; transform: translateY(14px);  } }

@media (prefers-reduced-motion: reduce) {
  ::view-transition-old(root),
  ::view-transition-new(root) { animation: none; }
}

__MIRRORED__

/* A footer page has no hero, so its content would otherwise start underneath
   the fixed nav. Qualified by ID because the sections it replaces carry their
   padding under ID selectors, which outrank anything written without one. */
__CLEARANCE__ { padding-top: 190px; }
@media (max-width: 700px) { __CLEARANCE__ { padding-top: 150px; } }

/* A footer page is as long as its contents, and the Careers page is at its
   shortest once the form has been replaced by the acknowledgement. Without
   this the footer stopped wherever the text did and the page's own background
   showed below it -- the firm's mark floating mid-screen over a white band.

   The nav is fixed and the notices are fixed, so neither is a flex item; only
   the content and the footer are, and the content takes the slack. */
body.page-inner {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}
body.page-inner main { flex: 1 0 auto; }
body.page-inner footer { flex-shrink: 0; }

/* Country, state and city read as one address, narrowing left to right, and
   none of them is left absurdly wide. Country carries a little more room
   because country names are the longest of the three. Below the width where
   two columns already stack, this stacks with them. */

/* The verification widget, when one is configured. Cloudflare sizes its own
   iframe; this only gives it room and keeps it on the form's rhythm. */
/* Only the visitor who is actually challenged ever sees this, so it reserves
   no room: an empty slot must not leave a gap above the button. */
.pdcm-turnstile { margin: 0; }
.pdcm-turnstile:not(:empty) { margin: 4px 0 22px; }

/* When it could not load. Reads as the notice it is, not as an error the
   applicant caused. */
.pdcm-turnstile-blocked {
  min-height: 0;
  font: 300 13.5px/1.7 "Lato", sans-serif;
  color: var(--charcoal);
  border-left: 2px solid var(--gold);
  padding: 2px 0 2px 14px;
}

.pdcm-apply-row-3 { grid-template-columns: 1.18fr 1fr 1fr; }
@media (max-width: 900px) { .pdcm-apply-row-3 { grid-template-columns: 1fr 1fr; } }
@media (max-width: 620px) { .pdcm-apply-row-3 { grid-template-columns: 1fr; } }

/* A footer page keeps the measure the panel had, so its text is not stranded
   across a wide screen. */
.page-body { max-width: 820px; margin: 0 auto; }
.page-body h2 {
  font-family: 'Cormorant SC', serif;
  font-weight: 500;
  font-size: clamp(36px, 4.4vw, 56px);
  letter-spacing: 0.04em;
  line-height: 1.16;
  color: var(--navy);
  border-bottom: 1px solid var(--platinum);
  padding-bottom: 28px;
  margin-bottom: 34px;
}
.page-body h3 {
  font-family: 'Cormorant SC', serif;
  font-weight: 500;
  font-size: 17px;
  letter-spacing: 0.05em;
  color: var(--navy);
  margin: 30px 0 12px;
}
.page-body p, .page-body li {
  font-size: 13.5px;
  line-height: 1.9;
  color: var(--charcoal);
  margin-bottom: 15px;
}
.page-body ul, .page-body ol { padding-left: 20px; margin-bottom: 15px; }
.page-body .pdcm-apply-done h3 { font-size: 26px; margin-top: 8px; }

/* No close button floats over a page, so the gutter that cleared one inside
   the panel is not wanted here. */
@media (max-width: 700px) {
  .page-body .pdcm-apply,
  .page-body .pdcm-required-note { padding-right: 0; }
}
"""
EXTRA_CSS = (EXTRA_CSS
             .replace("__MIRRORED__", "\n".join(mirrored))
             .replace("__CLEARANCE__", CLEARANCE))
for token in ("__MIRRORED__", "__CLEARANCE__"):
    if token in EXTRA_CSS:
        sys.exit("FAIL: unfilled " + token)

sheet = css + EXTRA_CSS
# A url() in a stylesheet resolves against the stylesheet, not the page. Left
# relative these are fetched from /assets/css/ and 404 on every page.
for name in ("tulsa%20skyline.jpg", "tulsa-skyline-hires.webp"):
    if 'url("%s")' % name not in sheet:
        sys.exit("FAIL: expected url(%s) in the stylesheet" % name)
    sheet = sheet.replace('url("%s")' % name, 'url("/%s")' % name)

CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
CSS_OUT.write_text(sheet, encoding="utf-8")


js = "\n".join(scripts)

# ── The hero's dissolve, driven by scroll ───────────────────────────
DISSOLVE_JS = """
/* The hero's lower edge fades into the section below it rather than ending on
   a line. What scroll changes is the length of that fade; the stylesheet
   keeps the bottom-most row at the paper colour at every moment, so the two
   sides always meet.

   The measure is how far the hero's lower edge has risen off the bottom of
   the window, not raw scroll distance -- the edge sits exactly on the bottom
   of the window at rest, so it is the moment it lifts that matters, and the
   same measure run backwards unwinds the fade as you scroll back up. */
(function () {
  "use strict";

  var hero = document.querySelector(".hero");
  if (!hero) return;

  /* The fade's full length, as a fraction of the hero's height. Longer is
     softer, and the limit is the text the gradient passes behind: measured
     over the sub-headline at the worst moment, 0.58 gives a contrast ratio
     of 7.1, 0.66 gives 4.8, and 0.74 gives 3.1 -- below the 4.5 that small
     text needs, and visibly washed. So this is as long as it goes. */
  var REACH = 0.66;
  var OVER = 340;     /* how far the edge rises before the fade is full */

  /* How far before the edge reaches the bottom of the window the fade
     begins, as a share of the distance available -- the hero's height less
     the window's. Fixed pixels cannot work here: the room depends on the
     window, and a lead longer than the room would leave the fade already
     part-resolved before a visitor has scrolled at all. The remaining fifth
     is the slack that guarantees it starts from nothing. */
  var LEAD_SHARE = 0.8;

  var reduce = false;
  try {
    reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  } catch (e) {}

  /* ── Why the value is eased in time as well as in scroll ──────────
     A wheel notch is a jump, not a movement: one click of the wheel is
     something like a hundred pixels arriving at once, and the hero has only
     a few hundred pixels of travel in which the whole fade has to happen.
     Mapping the fade straight onto scroll position therefore put most of the
     effect into each single click, which is what made it read as steps
     rather than as a dissolve.

     So scroll sets a target and the drawn value walks toward it, covering
     about nine tenths of the remaining distance every quarter second. A
     click still moves the target the same distance; it is the walk that the
     eye follows, and the walk is continuous. Stop scrolling mid-way and the
     fade keeps settling for a moment, which is the behaviour of something
     with weight. */
  var TAU = 0.25;           /* seconds to cover ~63% of what remains */
  var SETTLED = 0.0006;     /* close enough to stop the loop */

  var target = 0;
  var shown = 0;
  var running = false;
  var lastTime = 0;

  function measure() {
    var h = hero.offsetHeight || window.innerHeight;
    /* Start a little before the edge actually crosses, so it arrives with a
       fade already behind it rather than appearing as a line that then
       softens. Measured: without the lead the first visible moment carried a
       step of 24, against 5 everywhere after it. */
    var lead = Math.max(0, (h - window.innerHeight) * LEAD_SHARE);
    var risen = window.innerHeight - hero.getBoundingClientRect().bottom + lead;
    var t = risen / (OVER + lead);
    t = t < 0 ? 0 : t > 1 ? 1 : t;
    return reduce ? 1 : t * t * (3 - 2 * t);
  }

  function paint() {
    var px = shown * REACH * (hero.offsetHeight || window.innerHeight);
    /* The custom property still drives the mask on the vignette; the shader
       reads the same number to do the fade itself. */
    hero.style.setProperty("--hero-fade", px.toFixed(1) + "px");
    window.pdcmHeroFade = px;
  }

  function step(now) {
    var dt = lastTime ? Math.min((now - lastTime) / 1000, 0.1) : 0.016;
    lastTime = now;

    /* Frame-rate independent: the same fraction of the gap per unit of time,
       whatever the display is doing. */
    shown += (target - shown) * (1 - Math.exp(-dt / TAU));

    if (Math.abs(target - shown) < SETTLED) {
      shown = target;
      running = false;
      lastTime = 0;
      paint();
      return;
    }
    paint();
    window.requestAnimationFrame(step);
  }

  function onScroll() {
    target = measure();
    if (!running) {
      running = true;
      lastTime = 0;
      window.requestAnimationFrame(step);
    }
  }

  window.addEventListener("scroll", onScroll, { passive: true });
  window.addEventListener("resize", function () {
    /* A resize is not a gesture; there is nothing to follow, so land on the
       answer rather than gliding to it. */
    target = measure();
    shown = target;
    paint();
  }, { passive: true });

  target = measure();
  shown = target;
  paint();
})();
"""
js = js + "\n" + DISSOLVE_JS

# ── The entry notice ────────────────────────────────────────────────
# Once per visit, on whichever page the visitor arrives at. It was reopening
# every time someone came back to the landing page from Privacy or Careers,
# which is not a stricter gate, only a more irritating one. A new visit, a new
# tab or a reopened browser still gets it.
#
# A refresh must still open on the landing view rather than wherever the
# reader had scrolled to, and that was previously a side effect of the notice
# reopening. It is now done in its own right, so suppressing the notice does
# not quietly take it away with it.
GATE_OLD = """    clearEntryState();
    pinToTop();
    window.setTimeout(openEntryDisclaimer, 80);"""
GATE_NEW = """    var SEEN = "pdcm-entry-notice-acknowledged";
    var seen = false;
    try { seen = window.sessionStorage.getItem(SEEN) === "1"; } catch (e) {}

    if (!seen) {
      clearEntryState();
      pinToTop();
      window.setTimeout(openEntryDisclaimer, 80);
    } else {
      clearEntryState();
      /* Still open on the landing view. A hash means the reader asked for a
         particular section, so that is left alone. */
      if (!window.location.hash) pinToTop();
    }"""
if js.count(GATE_OLD) != 1:
    sys.exit("FAIL: entry notice opening sequence not found")
js = js.replace(GATE_OLD, GATE_NEW)

ACK_OLD = """        event.preventDefault();
        closeEntryDisclaimer();"""
ACK_NEW = """        event.preventDefault();
        try { window.sessionStorage.setItem(SEEN, "1"); } catch (e) {}
        closeEntryDisclaimer();"""
if js.count(ACK_OLD) != 1:
    sys.exit("FAIL: entry notice acknowledgement not found")
js = js.replace(ACK_OLD, ACK_NEW)

if "application=received" in js:
    sys.exit("FAIL: a return-trip parameter is back; the form answers in place now")

JS_OUT.parent.mkdir(parents=True, exist_ok=True)
JS_OUT.write_text(
    "/* Generated by src/build_pages.py from src/site.html. Edit the source,\n"
    "   not this file. */\n" + js, encoding="utf-8")


# ── Links ───────────────────────────────────────────────────────────
# The nav keeps its anchors: the main page is one page again. Only the footer
# changes, from panels that opened in place to pages with addresses.
PANEL_HREF = {
    'careers': '<a href="#" data-modal-trigger="careersModal">Careers</a>',
    'privacy': '<a href="#" data-modal-trigger="privacyModal">Privacy</a>',
    'terms': '<a href="#" data-modal-trigger="termsModal">Terms of Use</a>',
    'disclaimer': '<a href="#" data-modal-trigger="disclaimerModal">Disclaimer</a>',
}
PAGE_HREF = {
    'careers': '<a href="/careers/">Careers</a>',
    'privacy': '<a href="/privacy/">Privacy</a>',
    'terms': '<a href="/terms/">Terms of Use</a>',
    'disclaimer': '<a href="/disclaimer/">Disclaimer</a>',
}

def footer_for(on_page=None):
    out = footer
    for key, old in PANEL_HREF.items():
        if out.count(old) != 1:
            sys.exit("FAIL: footer link for %s not found" % key)
        new = PAGE_HREF[key]
        if key == on_page:
            new = new.replace('">', '" aria-current="page">')
        out = out.replace(old, new)
    return out

def absolutise(markup):
    return (markup.replace('src="assets/', 'src="/assets/')
                  .replace('href="assets/', 'href="/assets/')
                  .replace('src="tulsa', 'src="/tulsa'))

# On a footer page the nav anchors have to point back at the main page.
def nav_for(inner):
    out = nav
    if inner:
        out = out.replace('href="#top"', 'href="/"')
        for sid in ("firm", "approach", "values", "contact"):
            out = out.replace('href="#%s"' % sid, 'href="/#%s"' % sid)
    return out


PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{restoration}
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="canonical" href="https://philipdavidcapital.com{path}">
{fonts}
<link rel="stylesheet" href="/assets/css/site.css">
</head>
<body{bodyclass}>

{nav}

{content}

{footer}

{gate}

<script src="/assets/js/vendor/lenis.min.js"></script>
<script src="/assets/js/site.js"></script>
</body>
</html>
"""

FOOTER_PAGES = [
    dict(key="careers", out="careers/index.html", path="/careers/",
         title="Careers — Philip David Capital Management",
         description="The firm hires infrequently and deliberately. Candidates are welcome to "
                     "introduce themselves at any time."),
    dict(key="privacy", out="privacy/index.html", path="/privacy/",
         title="Privacy — Philip David Capital Management",
         description="How Philip David Capital Management handles information."),
    dict(key="terms", out="terms/index.html", path="/terms/",
         title="Terms of Use — Philip David Capital Management",
         description="Terms governing use of the Philip David Capital Management website."),
    dict(key="disclaimer", out="disclaimer/index.html", path="/disclaimer/",
         title="Disclaimer — Philip David Capital Management",
         description="Important disclosures regarding Philip David Capital Management."),
]

written = []

# ── The main page ───────────────────────────────────────────────────
main_html = PAGE.format(
    restoration=restoration,
    title="Philip David Capital Management — A Private Family Office in Tulsa, Oklahoma",
    description="Philip David Capital Management is a private family office headquartered in "
                "Tulsa, Oklahoma, managing family capital with quality, structure, and "
                "long-term foresight.",
    path="/",
    fonts=fonts,
    bodyclass="",
    nav=absolutise(nav_for(False)),
    content=absolutise(hero + "\n\n" + "\n\n".join(sections)),
    footer=absolutise(footer_for()),
    gate=absolutise(entry_gate),
)
(ROOT / "index.html").write_text(main_html, encoding="utf-8")
written.append(("index.html", len(main_html)))

# ── The footer pages ────────────────────────────────────────────────
for page in FOOTER_PAGES:
    content = ('<main class="page">\n<section id="page">\n  <div class="inner">\n'
               '    <div class="page-body">\n%s\n    </div>\n  </div>\n</section>\n</main>'
               % PANELS[page["key"]])
    html = PAGE.format(
        restoration=restoration, title=page["title"], description=page["description"],
        path=page["path"], fonts=fonts,
        bodyclass=' class="page-inner page-light"',
        nav=absolutise(nav_for(True)),
        content=absolutise(content),
        footer=absolutise(footer_for(page["key"])),
        gate=absolutise(entry_gate),
    )
    dest = ROOT / page["out"]
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(html, encoding="utf-8")
    written.append((page["out"], len(html)))

# ── 404 ─────────────────────────────────────────────────────────────
NOT_FOUND = """<main class="page">
<section id="notfound">
  <div class="inner">
    <div class="page-body">
      <h2>Page not found</h2>
      <p>The page you asked for is not here. It may have moved, or the address may be mistyped.</p>
      <p><a href="/">Return to the home page</a>.</p>
    </div>
  </div>
</section>
</main>"""
nf = PAGE.format(
    restoration=restoration, title="Page not found — Philip David Capital Management",
    description="The requested page could not be found.", path="/404.html", fonts=fonts,
    bodyclass=' class="page-inner page-light"',
    nav=absolutise(nav_for(True)), content=NOT_FOUND,
    footer=absolutise(footer_for()), gate=absolutise(entry_gate),
)
(ROOT / "404.html").write_text(nf, encoding="utf-8")
written.append(("404.html", len(nf)))

for name, size in written:
    print(f"  {name:24} {size:>9,} bytes")
print(f"\n  assets/css/site.css      {CSS_OUT.stat().st_size:>9,} bytes")
print(f"  assets/js/site.js        {JS_OUT.stat().st_size:>9,} bytes")
