#!/usr/bin/env python3
"""Build the multi-page site from src/site.html.

src/site.html stays the single source of truth for every style, script and
piece of markup. This script splits it into one page per nav destination and
lifts the shared CSS and JS into files the browser can cache across a
navigation -- which is what lets the view transition between pages look
instant rather than like a reload.

Nothing here rewrites copy. Sections move wholesale.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = (ROOT / "src/site.html").read_text(encoding="utf-8")

CSS_OUT = ROOT / "assets/css/site.css"
JS_OUT = ROOT / "assets/js/site.js"


def one(pattern, label, flags=re.S):
    m = re.findall(pattern, SRC, flags)
    if len(m) != 1:
        sys.exit(f"FAIL [{label}]: expected 1 match, found {len(m)}")
    return m[0]


# ── Head ────────────────────────────────────────────────────────────
head = one(r"<head>(.*?)</head>", "head")
restoration = one(r'(<script id="pdcm-scroll-restoration">.*?</script>)', "restoration")
fonts = "\n".join(re.findall(r'<link rel="preconnect"[^>]*>|<link href="https://fonts\.googleapis[^>]*>', head))
if not fonts:
    sys.exit("FAIL: font links not found")

styles = re.findall(r"<style[^>]*>(.*?)</style>", head, re.S)
if len(styles) != 5:
    sys.exit(f"FAIL: expected 5 style blocks, found {len(styles)}")


# ── Body pieces ─────────────────────────────────────────────────────
body = one(r"<body[^>]*>(.*?)</body>", "body")

nav = one(r"(<nav id=\"nav\">.*?</nav>)", "nav")
hero = one(r"(<header class=\"hero\" id=\"top\">.*?</header>)", "hero")
footer = one(r"(<footer>.*?</footer>)", "footer")
entry_gate = one(r'(<div class="disclaimer-modal" id="entryDisclaimerModal".*?</div>\s*</div>\s*</div>)', "entry gate")

sections = {}
for sid in ("firm", "approach", "values", "contact"):
    sections[sid] = one(r'(<section id="%s".*?</section>)' % sid, "section " + sid)

# The three legal modals travel with every page. The careers modal does not:
# its contents become a page of their own.
legal = re.findall(r'(<div class="disclaimer-modal" id="(?:disclaimer|privacy|terms)Modal".*?</div>\s*</div>\s*</div>)', SRC, re.S)
if len(legal) != 3:
    sys.exit(f"FAIL: expected 3 legal modals, found {len(legal)}")

careers_inner = one(r'<div class="disclaimer-modal" id="careersModal".*?<div class="disclaimer-content">(.*?)\s*</div>\s*</div>\s*</div>', "careers content")

# ── Scripts, in document order ──────────────────────────────────────
scripts = re.findall(r"<script(?![^>]*\bsrc=)(?![^>]*pdcm-scroll-restoration)[^>]*>(.*?)</script>", body, re.S)
if len(scripts) < 7:
    sys.exit(f"FAIL: expected the page's scripts, found {len(scripts)}")


# ── Shared CSS ──────────────────────────────────────────────────────
# Every rule that styles the nav in its scrolled state is mirrored onto the
# inner pages, which have no hero to sit over and so need that treatment from
# the first frame. Mirroring rather than restating means the two can't drift.
css = "\n".join(styles)

mirrored = []
for rule in re.findall(r"([^{}]*nav\.scrolled[^{}]*)\{([^{}]*)\}", css):
    sel = ", ".join(
        s.strip().replace("nav.scrolled", "body.page-light nav")
        for s in rule[0].split(",") if "nav.scrolled" in s
    )
    if sel:
        mirrored.append(f"{sel} {{{rule[1]}}}")
if len(mirrored) < 4:
    sys.exit(f"FAIL: expected to mirror the nav.scrolled rules, mirrored {len(mirrored)}")

EXTRA_CSS = """

/* ════════════════════════════════════════════════
   MULTI-PAGE — generated by src/build_pages.py
   ════════════════════════════════════════════════ */

/* Cross-document view transitions. Chrome and Safari animate between pages;
   Firefox ignores the at-rule and navigates normally, which is the correct
   fallback rather than a broken one. Naming the nav and footer keeps them
   still while the page beneath them changes, so a navigation reads as the
   content turning over rather than the whole site reloading. */
@view-transition { navigation: auto; }

nav { view-transition-name: pdcm-nav; }
footer { view-transition-name: pdcm-footer; }

::view-transition-old(root) {
  animation: pdcmPageOut 0.30s cubic-bezier(.4, 0, 1, 1) both;
}
::view-transition-new(root) {
  animation: pdcmPageIn 0.46s cubic-bezier(.16, 1, .3, 1) both;
}
@keyframes pdcmPageOut { to   { opacity: 0; transform: translateY(-10px); } }
@keyframes pdcmPageIn  { from { opacity: 0; transform: translateY(14px);  } }

@media (prefers-reduced-motion: reduce) {
  ::view-transition-old(root),
  ::view-transition-new(root) { animation: none; }
}

/* The nav on an inner page. */
%(mirrored)s

/* An inner page has no hero, so its first section would otherwise start
   underneath the fixed nav. Each section carries its own padding under an ID
   selector, which outranks anything written without one -- so these are
   qualified by ID too, or the rule silently loses and the heading sits behind
   the nav. */
%(clearance)s { padding-top: 190px; }
@media (max-width: 700px) { %(clearance)s { padding-top: 150px; } }

/* Approach keeps its navy ground as a page, so the nav stays in its light
   form there and the page's own background matches to the overscroll edge. */
body.page-dark { background: var(--navy); }
body.page-dark nav.scrolled {
  background: rgba(25, 44, 68, 0.92);
  border-bottom: 1px solid rgba(234, 208, 156, 0.14);
}
body.page-dark nav.scrolled .nav-logo .lockup-w { display: block; }
body.page-dark nav.scrolled .nav-logo .lockup-n { display: none; }
body.page-dark nav.scrolled .nav-links a { color: var(--cream); }
body.page-dark nav.scrolled .nav-links a:hover { color: var(--gold); }
body.page-dark nav.scrolled .nav-li-link {
  border-color: rgba(246, 243, 236, 0.4);
  color: var(--cream) !important;
}

/* The current page, marked in the nav. */
.nav-links a[aria-current="page"] { color: var(--gold); }
.nav-links a[aria-current="page"]::after { width: 100%%; }
body.page-light .nav-links a[aria-current="page"] { color: var(--capital-blue); }

/* The Careers application, now a page rather than a panel. It keeps the
   modal's measure so the form is not stranded across a wide screen. */
.careers-page { max-width: 820px; margin: 0 auto; }
.careers-page h2 {
  font-family: 'Cormorant SC', serif;
  font-weight: 500;
  font-size: clamp(36px, 4.4vw, 56px);
  letter-spacing: 0.04em;
  line-height: 1.16;
  color: var(--navy);
  border-bottom: 1px solid var(--platinum);
  padding-bottom: 28px;
  margin-bottom: 34px;
}
.careers-page > p {
  font-size: 14.5px;
  line-height: 1.9;
  color: var(--charcoal);
  margin-bottom: 18px;
}
.careers-page .pdcm-apply-done h3 {
  font-family: 'Cormorant SC', serif;
  font-weight: 500;
  font-size: 26px;
  letter-spacing: 0.05em;
  color: var(--navy);
  margin-bottom: 16px;
}
/* No close button floats over this form, so the gutter that cleared one
   inside the modal is not wanted here. */
@media (max-width: 700px) {
  .careers-page .pdcm-apply,
  .careers-page .pdcm-required-note { padding-right: 0; }
}
""" % {
    "mirrored": "\n".join(mirrored),
    "clearance": ",\n".join("body.page-inner main > section#" + i
                            for i in ("firm", "approach", "values", "contact", "careers", "notfound")),
}

# A url() in a stylesheet resolves against the stylesheet, not the page. Left
# relative, these would be fetched from /assets/css/ and 404 on every page that
# uses them, so they are made absolute along with everything else.
sheet = css + EXTRA_CSS
for name in ("tulsa%20skyline.jpg", "tulsa-skyline-hires.webp"):
    if 'url("%s")' % name not in sheet:
        sys.exit("FAIL: expected url(%s) in the stylesheet" % name)
    sheet = sheet.replace('url("%s")' % name, 'url("/%s")' % name)

CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
CSS_OUT.write_text(sheet, encoding="utf-8")


# ── Shared JS ───────────────────────────────────────────────────────
js = "\n".join(scripts)

# The entry notice was written for a single page, where every load is a fresh
# arrival. Across six pages it would reappear on every navigation, so it now
# shows once per browser session. A new visit, a new tab, or a reopened
# browser still gets it; moving between pages does not.
GATE_OLD = """    clearEntryState();
    pinToTop();
    window.setTimeout(openEntryDisclaimer, 80);"""
GATE_NEW = """    var SEEN = "pdcm-entry-notice-acknowledged";
    var seen = false;
    try { seen = window.sessionStorage.getItem(SEEN) === "1"; } catch (e) {}

    if (!seen) {
      clearEntryState();
      pinToTop();
      window.setTimeout(openEntryDisclaimer, 80);
    }"""
if js.count(GATE_OLD) != 1:
    sys.exit("FAIL: entry notice opening sequence not found")
js = js.replace(GATE_OLD, GATE_NEW)

ACK_OLD = """        event.preventDefault();
        closeEntryDisclaimer();"""
ACK_NEW = """        event.preventDefault();
        try { window.sessionStorage.setItem(SEEN, "1"); } catch (e) {}
        closeEntryDisclaimer();"""
if js.count(ACK_OLD) != 1:
    sys.exit("FAIL: entry notice acknowledgement not found")
js = js.replace(ACK_OLD, ACK_NEW)

# The application now lives at /careers/, so the relay returns the candidate
# there rather than to whichever page the form happened to be opened from.
RET_OLD = 'var RETURN_TO = location.origin + location.pathname + "?application=received";'
RET_NEW = 'var RETURN_TO = location.origin + "/careers/?application=received";'
if js.count(RET_OLD) != 1:
    sys.exit("FAIL: return address not found")
js = js.replace(RET_OLD, RET_NEW)

JS_OUT.parent.mkdir(parents=True, exist_ok=True)
JS_OUT.write_text(
    "/* Generated by src/build_pages.py from src/site.html. Edit the source,\n"
    "   not this file. */\n" + js, encoding="utf-8")


# ── Links ───────────────────────────────────────────────────────────
# The nav destinations become real URLs. Directory paths rather than .html so
# the address bar reads philipdavidcapital.com/approach, the way the rest of
# the industry writes them.
DEST = {"firm": "/firm/", "approach": "/approach/", "values": "/values/", "contact": "/contact/"}

def link_up(markup, current=None):
    out = markup.replace('href="#top" class="nav-logo"', 'href="/" class="nav-logo"')
    for sid, href in DEST.items():
        out = out.replace('href="#%s"' % sid, 'href="%s"' % href)
    out = out.replace('<a href="#" data-modal-trigger="careersModal">Careers</a>',
                      '<a href="/careers/">Careers</a>')
    if current:
        out = out.replace('href="%s"' % DEST[current],
                          'href="%s" aria-current="page"' % DEST[current], 1) if current in DEST else out
    return out

# Assets are referenced from nested pages too, so their paths must be
# absolute rather than relative to the page that happens to use them.
def absolutise(markup):
    return (markup
            .replace('src="assets/', 'src="/assets/')
            .replace('href="assets/', 'href="/assets/')
            .replace('url("tulsa', 'url("/tulsa')
            .replace('src="tulsa', 'src="/tulsa'))


# Anyone holding a link to the old single page -- philipdavidcapital.com/#approach
# -- would otherwise land on a home page with a dead anchor. This sends them to
# the page that section became. It runs before anything renders, so the wrong
# page is never painted.
HASH_REDIRECT = """<script id="pdcm-legacy-anchor">
  /* The sections of the former single page are now pages of their own. A
     bookmark or an inbound link to the old anchor still reaches its content. */
  (function () {
    var moved = { "#firm": "/firm/", "#approach": "/approach/",
                  "#values": "/values/", "#contact": "/contact/" };
    var to = moved[window.location.hash];
    if (to) window.location.replace(to);
  })();
</script>"""


PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{restoration}
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="canonical" href="https://philipdavidcapital.com{path}">
{fonts}
<link rel="stylesheet" href="/assets/css/site.css">
</head>
<body{bodyclass}>

{nav}

{content}

{footer}

{modals}

{gate}

<script src="/assets/js/vendor/lenis.min.js"></script>
<script src="/assets/js/site.js"></script>
</body>
</html>
"""

FIRM_DESC = ("Philip David Capital Management is a private family office headquartered in "
             "Tulsa, Oklahoma, managing family capital with quality, structure, and "
             "long-term foresight.")

PAGES = [
    dict(path="/", out="index.html", key=None, dark=True,
         title="Philip David Capital Management — A Private Family Office in Tulsa, Oklahoma",
         description=FIRM_DESC, content=hero, hero=True),
    dict(path="/firm/", out="firm/index.html", key="firm", dark=False,
         title="The Firm — Philip David Capital Management",
         description="A small firm by design, managing family capital from Tulsa, Oklahoma."),
    dict(path="/approach/", out="approach/index.html", key="approach", dark=True,
         title="Approach — Philip David Capital Management",
         description="How Philip David Capital Management approaches the management of family capital."),
    dict(path="/values/", out="values/index.html", key="values", dark=False,
         title="Values — Philip David Capital Management",
         description="Responsibility, discipline, patience, independence and accountability."),
    dict(path="/contact/", out="contact/index.html", key="contact", dark=False,
         title="Contact — Philip David Capital Management",
         description="Contact Philip David Capital Management in Tulsa, Oklahoma."),
    dict(path="/careers/", out="careers/index.html", key=None, dark=False,
         title="Careers — Philip David Capital Management",
         description="The firm hires infrequently and deliberately. Candidates are welcome to "
                     "introduce themselves at any time."),
]

modals_markup = absolutise("\n\n".join(legal))
gate_markup = absolutise(entry_gate)
footer_markup = absolutise(link_up(footer))

written = []
for page in PAGES:
    key = page["key"]
    if "content" in page:
        content = page["content"]
    elif key:
        content = '<main class="page">\n%s\n</main>' % sections[key]
    else:
        content = ('<main class="page">\n<section id="careers">\n  <div class="inner">\n'
                   '    <div class="careers-page">\n%s\n    </div>\n  </div>\n</section>\n</main>'
                   % careers_inner)

    classes = []
    if not page.get("hero"):
        classes.append("page-inner")
    classes.append("page-dark" if page["dark"] else "page-light")

    html = PAGE.format(
        restoration=restoration + ("\n" + HASH_REDIRECT if page["path"] == "/" else ""),
        title=page["title"],
        description=page["description"],
        path=page["path"],
        fonts=fonts,
        bodyclass=' class="%s"' % " ".join(classes),
        nav=absolutise(link_up(nav, key)),
        content=absolutise(content),
        footer=footer_markup,
        modals=modals_markup,
        gate=gate_markup,
    )

    dest = ROOT / page["out"]
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(html, encoding="utf-8")
    written.append((page["out"], len(html)))

# GitHub Pages serves 404.html for any path it does not recognise. Without one
# a visitor who mistypes a URL gets GitHub's own page, carrying none of the
# firm's identity.
NOT_FOUND = """<main class="page">
<section id="notfound">
  <div class="inner">
    <div class="careers-page">
      <h2>Page not found</h2>
      <p>The page you asked for is not here. It may have moved, or the address may be mistyped.</p>
      <p><a href="/">Return to the home page</a>, or use the navigation above.</p>
    </div>
  </div>
</section>
</main>"""

(ROOT / "404.html").write_text(PAGE.format(
    restoration=restoration,
    title="Page not found — Philip David Capital Management",
    description="The requested page could not be found.",
    path="/404.html",
    fonts=fonts,
    bodyclass=' class="page-inner page-light"',
    nav=absolutise(link_up(nav)),
    content=NOT_FOUND,
    footer=footer_markup,
    modals=modals_markup,
    gate=gate_markup,
), encoding="utf-8")
written.append(("404.html", (ROOT / "404.html").stat().st_size))

for name, size in written:
    print(f"  {name:24} {size:>9,} bytes")
print(f"\n  assets/css/site.css      {CSS_OUT.stat().st_size:>9,} bytes")
print(f"  assets/js/site.js        {JS_OUT.stat().st_size:>9,} bytes")
